do nothing
[Modelarts Service Log]user: uid=1101(work) gid=1101(work) groups=1101(work)
[Modelarts Service Log]pwd: /home/work
[Modelarts Service Log]app_url: s3://resnext-tk/MA-ResNeXt-in-tensorflow-master-11-03-14-34/code/
[Modelarts Service Log]boot_file: code/cifar10_train.py
[Modelarts Service Log]log_url: /tmp/log/MA-ResNeXt-in-tensorflow-master-11-03-14-34.log
[Modelarts Service Log]command: code/cifar10_train.py --data_url=s3://resnext-tk/ResNeXt-in-tensorflow-master/cifar10_data/cifar-10-batches-py/ --train_url=s3://resnext-tk/MA-ResNeXt-in-tensorflow-master-11-03-14-34/output/V0001/ --num_gpus=1
[Modelarts Service Log]MODELARTS_IPOIB_DEVICE: 
[Modelarts Service Log]dependencies_file_dir: /home/work/user-job-dir/code
[Modelarts Service Log][modelarts_create_log] modelarts-pipe found
[Modelarts Service Log]handle inputs of training job
INFO:root:Using MoXing-v1.17.1-47ce498c
INFO:root:Using OBS-Python-SDK-3.1.2
[ModelArts Service Log][INFO][2020/11/03 14:37:33]: env MA_INPUTS is not found, skip the inputs handler
INFO:root:Using MoXing-v1.17.1-47ce498c
INFO:root:Using OBS-Python-SDK-3.1.2
[ModelArts Service Log]2020-11-03 14:37:34,640 - modelarts-downloader.py[line:619] - INFO: Main: modelarts-downloader starting with Namespace(dst='./', recursive=True, skip_creating_dir=False, src='s3://resnext-tk/MA-ResNeXt-in-tensorflow-master-11-03-14-34/code/', trace=False, type='common', verbose=False)
[ModelArts Service Log]modelarts-pipe: will create log file /tmp/log/MA-ResNeXt-in-tensorflow-master-11-03-14-34.log
[ModelArts Service Log]modelarts-pipe: will create log file /tmp/log/MA-ResNeXt-in-tensorflow-master-11-03-14-34.log
[ModelArts Service Log]modelarts-pipe: will write log file /tmp/log/MA-ResNeXt-in-tensorflow-master-11-03-14-34.log
[ModelArts Service Log]modelarts-pipe: param for max log length: 1073741824
[ModelArts Service Log]modelarts-pipe: param for whether exit on overflow: 0
/home/work/user-job-dir
[Modelarts Service Log][modelarts_logger] modelarts-pipe found
Traceback (most recent call last):
  File "code/cifar10_train.py", line 5, in <module>
    from resNeXt import *
  File "/cache/user-job-dir/code/resNeXt.py", line 10, in <module>
    from hyper_parameters import *
  File "/cache/user-job-dir/code/hyper_parameters.py", line 67, in <module>
    train_dir = 'logs_' + FLAGS.version + '/'
  File "/home/work/anaconda/lib/python2.7/site-packages/tensorflow/python/platform/flags.py", line 84, in __getattr__
    wrapped(_sys.argv)
  File "/home/work/anaconda/lib/python2.7/site-packages/absl/flags/_flagvalues.py", line 633, in __call__
    name, value, suggestions=suggestions)
absl.flags._exceptions.UnrecognizedFlagError: Unknown command line flag 'data_url'
[ModelArts Service Log]modelarts-pipe: total length: 709
[Modelarts Service Log]Training end with return code: 1
[Modelarts Service Log]Training completed.
